on: 
  push:
  schedule: 
    - cron:  '0 * * * *' 

name: DATA

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Run Scripts
        run: |
          Rscript vaccines.R
          Rscript data.R
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add vaccines.csv.gz vaccines-latest.csv data.csv.gz data-latest.csv datawrapper.csv
          git commit --allow-empty -m "Automated Update"
          git push
