name: AL
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Free space:"
          df -h
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Build
        run: |
          Rscript state.R AL
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add states/AL.csv
          git commit -m "Automatic Update"
          git push
