on: 
  push:
  schedule: 
    - cron:  '0 6 * * *' 

name: MASTER

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Run Scripts
        run: |
          Rscript vaccines.R
          Rscript master.R
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add vaccines.csv vaccines.csv.gz master.csv master.csv.gz master-latest.csv master-latest.csv.gz
          git commit --allow-empty -m "Automated Update"
          git push
