on:
  push:
  schedule: 
    - cron:  '0 0 * * *' 

name: São Paulo

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      STATE_CODE: SP
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 4096
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Download
        run: |
          Rscript download.R ${{ env.STATE_CODE }}
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add download/${{ env.STATE_CODE }}.csv
          git commit --allow-empty -m "Automated Update"
          git pull --rebase
          git push
